### ISSUE TITLE
可以搞QQ小号就是机器人吗，官方的只能企业才可以目前

### ISSUE THREAD

**Issue by wqzai** [NGWORKS/qq_guild_bot#3]

**Comment by hegugu-ng** [comment]
您好，目前我这边就是企业开发者，官方目前消息下周（29号）之后，可能会开放个人开发者注册。到时候请您关注一下。

**Comment by wqzai** [comment]
好的，感谢大佬！！！🥳



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月28日(周日) 晚上11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NGWORKS/qq_guild_bot] 可以搞QQ小号就是机器人吗，官方的只能企业才可以目前 (Issue #3)




 
您好，目前我这边就是企业开发者，官方目前消息下周（29号）之后，可能会开放个人开发者注册。到时候请您关注一下。

**Comment by hegugu-ng** [comment]
好的，没有什么问题我就关闭这个issues了
